apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: orion-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orion
  template:
    metadata:
      labels:
        app: orion
    spec:
      containers:
        - name: orion-pod
          image: orion:1.0
          env:
            - name: USERNAME
              value: your username
            - name: CONSUMER_KEY
              value: your consumer key
            - name: CONSUMER_SECRET
              value: your consumer secret
            - name: ACCESS_TOKEN
              value: your access token
            - name: ACCESS_SECRET
              value: your access secret